### PR TITLE
Update and rename README to README.md

### PR DESCRIPTION
**Pull request by andreasabel**
Change README to markdown, so we can use syntax coloring for haskell.

### CODE REVIEW

**Comment by andreasabel** [comment]
@sol: Can I be added as maintainer (here and on hackage) so that I can merge and release this PR?

**Comment by andreasabel** [comment]
Ping @sol.

**Comment by sol** [comment]
@andreasabel done

**Comment by andreasabel** [comment]
Thanks, @sol!  I made a cosmetic release (v1.2.5.2), which added README and CHANGELOG, and fixed one warning.

**Pull request merged**
